### ISSUE TITLE
Reporting API documentation is incorrect

### ISSUE THREAD

**Issue by chrsm** [adzerk/adzerk-api#20]
Hi folks,

It seems that the documentation for the queued reports API is incorrect: https://github.com/adzerk/adzerk-api/wiki/Reporting-API#poll-for-the-result-of-a-queued-report suggests that the "Result" property will be null for an incomplete report, rather than not present at all. While it's a minor point, it is not necessarily correct:

    [2015-08-05 20:01:13] https://api.adzerk.net/v1/report/queue/<id>
    GET /v1/report/queue/<id> HTTP/1.1
    Host: api.adzerk.net
    Accept-Encoding: gzip, deflate
    Expect:
    User-Agent: Httpful/0.1.7 (cURL/7.15.5 PHP/5.3.28 (Linux))
    Accept: */*; q=0.5, text/plain; q=0.8, text/html;level=3;
    X-Adzerk-ApiKey: <api key>
    
    
    Response:
    HTTP/1.1 200 OK
    Cache-Control: private
    Content-Type: application/json
    Date: Wed, 05 Aug 2015 20:01:13 GMT
    Server: nginx/1.1.19
    Set-Cookie: ASP.NET_SessionId=<session>; path=/
    X-AspNet-Version: 4.0.30319
    X-AspNetMvc-Version: 2.0
    Content-Length: 56
    Connection: keep-alive
    
    {"Id":"<id>","Status":1}

Additionally, not all reports seem to contain "Result" when they're actually marked as complete:

    [2015-08-05 19:58:16] https://api.adzerk.net/v1/report/queue/<id>
    GET /v1/report/queue/<id> HTTP/1.1
    Host: api.adzerk.net
    Accept-Encoding: gzip, deflate
    Expect:
    User-Agent: Httpful/0.1.7 (cURL/7.15.5 PHP/5.3.28 (Linux))
    Accept: */*; q=0.5, text/plain; q=0.8, text/html;level=3;
    X-Adzerk-ApiKey: <apikey>
    
    
    Response:
    HTTP/1.1 200 OK
    Cache-Control: private
    Content-Type: application/json
    Date: Wed, 05 Aug 2015 19:58:16 GMT
    Server: nginx/1.1.19
    Set-Cookie: ASP.NET_SessionId=<session>; path=/
    X-AspNet-Version: 4.0.30319
    X-AspNetMvc-Version: 2.0
    Content-Length: 56
    Connection: keep-alive
    
    {"Id":"<id>","Status":2}

Any idea what's going on in the second case? According to the documentation, the `Result` key should be present at this point.

**Comment by karnowski** [comment]
You are correct the result merely returns a JSON object with an `Id` key and the report-id as a value.  We will update our docs to be more consistent.

The issue with `{"Id":"<id>","Status":2}` is usually due to a bug in the way we process reports.  We are currently working on several fixes to our Reporting system that should fix this issue.

The main causes of this bug are:

* really huge data sets (but this won't be a problem soon!)
* reports run during high load or concurrent report processing

The primary workaround we employ internally is to re-queue the report, and request the result with the new `report-id`.  

Please note our biggest development effort right now is our "Reporting 2.0" which will keep a similar API but change all the internals... getting rid of all these issues.

Thanks for your input!

**Comment by karnowski** [comment]
Docs updated.
