### ISSUE TITLE
Budget Capping Changes

### ISSUE THREAD

**Issue by chrsm** [adzerk/adzerk-api#24]
Per https://github.com/adzerk/adzerk-api/wiki/Budget-Capping-%28Beta%29/_compare/0cc8a3c%5E...0cc8a3c

I read this as only integer values will be accepted, but I want to make sure that's the case. We have some advertisers who have caps like:

- 5.25 / day
- 39.38 / day
- 16.60 / day

(etc)

So it seems that with this change, we will no longer be able to specify cents and need to round their per-day spend to the nearest dollar?

Just want to make sure so that we don't have any unexpected behavior down the road. Thanks

**Comment by daveyarwood** [comment]
Yes - budget caps are integers representing dollar amounts. There is no way to specify a more exact amount in cents.

Just to be clear, the commit you referenced was only a change to the spec, not the code itself. Budget caps have been in dollars since we implement them.

Hope that helps!

**Comment by karnowski** [comment]
Dave is right -- it was a documentation error that we said that we supported sub-dollar budget caps.  Unfortunately we literally just can't stop "on a dime" in most cases.  (Forgive the pun.)  The campaigns would over-serve.    

We recommend that you set the expectation with your advertisers that campaigns will sometimes over-serve slightly depending on the size of the cap and the speed of the traffic.  A larger cap gives us more room to slow down and then gently stop at the cap rather than blow past the cap and then abruptly halt.
